// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "AI-Robotics",
//   description: "Generated by AI-Robotics",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


import { Inter } from "next/font/google";
import { Box } from "@chakra-ui/react";
import { Toaster } from "react-hot-toast";
import Layoutprovider from "@/components/layout/layoutprovider";
import { Providers } from "./chakraprovider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MR Automation Solution",
  description: "Generated by MR Automation Solution",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <Box w={"100%"} overflow={"hidden"}>
          <Providers>
            <Layoutprovider>{children}</Layoutprovider>
          </Providers>
        </Box>
      </body>
    </html>
  );
};
export default RootLayout;